config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users

  Rails.application.routes.draw do
    root to: "pages#home"
    get 'home', to: 'pages#home'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'
    get 'about', to: 'pages#about'
    get 'link_to_shops', to: 'shops#index'
    get 'link_to_roasters', to: 'roasters#index'
    get 'link_to_farmers', to: 'farmers#index'
    get 'cards/show_card'

  end

  resources :roasters
  resources :shops
  resources :farmers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  def image_url
    "/images/#{self.id}.jpg"
  end
end

app/models/roaster.rb
class Roaster < ApplicationRecord

  def image_url
    "https://res.cloudinary.com/difj9msh3/image/upload/v1695482494/PHOTO-2023-09-23-16-06-21-2_impmgk.heic"
  end



end

app/models/shop.rb
class Shop < ApplicationRecord
  def image_url
    "/images/#{self.id}.jpg"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

def show_card
  @image_url = "https://res.cloudinary.com/difj9msh3/image/upload/v1695482480/IMG_0425_xtbfav.heic"
  @alt_text = "Alt Text for Image"
  @description = "Description of the picture"
  @link = "#"
end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show_card
    @image_url = "https://res.cloudinary.com/difj9msh3/image/upload/v1695482480/IMG_0425_xtbfav.heic"
    @alt_text = "Alt Text for Image"
    @description = "Description of the picture"
    @link = "https://res.cloudinary.com/difj9msh3/image/upload/v1695482480/IMG_0425_xtbfav.heic"
  end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_farmer, only: [:show, :edit, :update, :destroy]

  def index
    @farmers = Farmer.all
  end

  def show
  end

  def new
    @farmer = Farmer.new
  end

  def create
    @farmer = Farmer.new(farmer_params)

    if @farmer.save
      redirect_to @farmer, notice: 'Farmer was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @farmer.update(farmer_params)
      redirect_to @farmer, notice: 'Farmer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @farmer.destroy
    redirect_to farmers_url, notice: 'Farmer was successfully destroyed.'
  end

  private

  def set_farmer
    @farmer = Farmer.find(params[:id])
  end

  def farmer_params
    params.require(:farmer).permit(:name, :location, :crop_type)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :set_roaster, only: [:show, :edit, :update, :destroy]

  def index
    @roasters = Roaster.all
  end

  def show
  end

  def new
    @roaster = Roaster.new
  end

  def create
    @roaster = Roaster.new(roaster_params)

    if @roaster.save
      redirect_to @roaster, notice: 'Roaster was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @roaster.update(roaster_params)
      redirect_to @roaster, notice: 'Roaster was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @roaster.destroy
    redirect_to roasters_url, notice: 'Roaster was successfully destroyed.'
  end

  private

  def set_roaster
    @roaster = Roaster.find(params[:id])
  end


  def roaster_params
    params.require(:roaster).permit(:name, :location, :year_established, :image_url)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @shops = Shop.all
  end

  def show
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to @shop, notice: 'Shop was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: 'Shop was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_url, notice: 'Shop was successfully destroyed.'
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/farmers/_farmer_card.html.erb
<div class="card-content">
  <div class="left">
    <% if @farmer.present? %>
      <h3><%= @farmer.name %></h3>
      <p><%= @farmer.location %></p>
    <% else %>
      <p>Farmer not found.</p>
    <% end %>
    <button class="card-button">Button</button>
  </div>
</div>

app/views/farmers/index.html.erb
<!DOCTYPE html>

<head>
  <link rel="stylesheet" href="styles.css">
</head>

<body>

  <%= render 'shared/navbar' %>

  <%= render 'shared/footer' %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Coffee Consierge</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', '/app/assets/stylesheets/components/_navbar.scss', '/app/assets/stylesheet/components/_card.scss', media: 'all' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>

<head>
  <link rel="stylesheet" href="styles.css">
</head>

<body>

  <div class="background"></div>

    <%= render 'shared/navbar' %>

    <%= render 'shared/card' %>

    <%= render 'shared/card' %>

    <%= render 'shared/footer' %>

</body>

</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>

<head>
  <link rel="stylesheet" href="styles.css">
</head>

<body>

  <div class="background"></div>

    <%= render 'shared/navbar' %>

    <%= render 'shared/card' %>

    <%= render 'shared/form' %>

    <%= render 'shared/footer' %>

</body>

</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>

      <%= render 'shared/navbar' %>

      <div class="container">
        <div class="row">

          <div class="col-12 col-lg-8">
          </div>

          <%= render 'shared/news-card' %>

          <%= render 'shared/footer' %>

        <div class="col-12 col-lg-4">
      </div>
      </div>




  </body>
</html>


</html>

app/views/pages/shops/index.html.erb
<!DOCTYPE html>

<head>
  <link rel="stylesheet" href="styles.css">
</head>

<body>

  <div class="background"></div>

  <%= render 'shared/navbar' %>



  <%= render 'shared/footer' %>

</body>

</html>

app/views/roasters/_new.html.erb
<%= simple_form_for @roaster, html: { multipart: true } do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :year_established %>
  <%= f.input :image_url, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/roasters/_roaster_card.html.erb
<div class="card">
  <%= image_tag roaster.image_url, alt: roaster.name, class: "card-image" %>
  <div class="card-content">
    <h2><%= roaster.name %></h2>
    <p><%= roaster.location %></p>
    <p><%= roaster.types_of_coffee %></p>
  </div>
</div>

app/views/roasters/index.html.erb
<!DOCTYPE html>

<body>

  <%= render 'shared/navbar' %>

  <div class="container">
    <div class="container mt-4 align-items-start">
    <div class="row">
      <div class="row">
  <div class="col-12 col-lg-4">
    <%= render 'shared/card' %>
  </div>
  <div class="col-12 col-lg-8">
    <h1 class="mb-3">Roasters</h1>
    <p class="mb-4">Here is a list of all the roasters we have in our database.</p>
    <ul class="list-group">
      <% @roasters.each do |roaster| %>
        <li class="list-group-item border rounded mb-3">
          <%= link_to roaster.name, roaster_path(roaster), class: "d-block text-dark text-decoration-none" %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>

    </div>

  <%= render 'shared/footer' %>

</body>

</html>

app/views/shared/_card.html.erb
<div class="big-card">
  <div class="row">
    <% @roasters.each do |roaster| %>
      <div class="col-md-4">
        <div class="small-card">
          <img src="<%= roaster.image_url %>" class="card-img-top" alt="...">
          <div class="card-footer text-center py-4">
            <p class="card-text mb-2"><%= roaster.name %></p>
            <p class="card-text mb-2"><%= roaster.location %></p>
            <!-- Add any other properties you want to display -->
            <button class="btn btn-primary">View Details</button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Coffee Consierge</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>

    <div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    </div>

  </body>

app/views/shared/_footer.html.erb
  <footer class="footer">
    <div class="social-icons">
      <img src="https://res.cloudinary.com/difj9msh3/image/upload/v1694982969/instagram_fkr0xf.svg" alt="Instagram Icon">
      <img src="https://res.cloudinary.com/difj9msh3/image/upload/v1694983048/youtube_ainyld.svg" alt="YouTube Icon">
      <img src="https://res.cloudinary.com/difj9msh3/image/upload/v1694983101/whatsapp_gu9t28.svg" alt="Whatsapp Icon">
    </div>
  </footer>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Contact Us</h5>
        <%= form_for :contact, url: contact_path, method: :post, html: { class: 'contact-form' } do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', required: true %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', required: true %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control', required: true %>
          </div>
          <%= f.submit "Submit", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Coffee Consierge</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href='link_to_roasters'>Roasters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="link_to_farmers">Farmers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="link_to_shops">Shops</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Coffee Shop</a></li>
            <li><a class="dropdown-item" href="#">Barista Accesories</a></li>
            <li><a class="dropdown-item" href="#">About Us</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_news-card.html.erb
<div class="custom-margin">
  <p class="d-inline-flex gap-1">
    <a class="btn btn-secondary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="true" aria-controls="multiCollapseExample1">Industry news, Prices and iniciatives</a>
    <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="true" aria-controls="multiCollapseExample2">Sustainability</button>
    <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="true" aria-controls="multiCollapseExample1 multiCollapseExample2">All</button>
  </p>
  <div class="row">
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample1">
        <div class="card card-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tristique ultrices urna, a posuere eros gravida eu. Nulla interdum mauris ac nibh aliquam consequat. Phasellus vel malesuada elit. Sed vel lectus eu neque cursus malesuada vitae vitae turpis. Curabitur id nisi ut justo ullamcorper suscipit nec ac justo. Etiam cursus, ligula vel euismod posuere, dui orci bibendum sapien, in sollicitudin quam est ac nulla. Morbi vitae magna eu libero tincidunt facilisis et eu risus. Vivamus non purus nec neque consequat suscipit. Vivamus ut arcu eu odio bibendum pulvinar. Nullam semper velit et tortor tempus, non euismod tellus facilisis. Fusce vitae mi auctor, sollicitudin purus a, tincidunt justo. Sed imperdiet, lectus at efficitur vulputate,
        </div>
      </div>
    </div>
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample2">
        <div class="card card-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tristique ultrices urna, a posuere eros gravida eu. Nulla interdum mauris ac nibh aliquam consequat. Phasellus vel malesuada elit. Sed vel lectus eu neque cursus malesuada vitae vitae turpis. Curabitur id nisi ut justo ullamcorper suscipit nec ac justo. Etiam cursus, ligula vel euismod posuere, dui orci bibendum sapien, in sollicitudin quam est ac nulla. Morbi vitae magna eu libero tincidunt facilisis et eu risus. Vivamus non purus nec neque consequat suscipit. Vivamus ut arcu eu odio bibendum pulvinar. Nullam semper velit et tortor tempus, non euismod tellus facilisis. Fusce vitae mi auctor, sollicitudin purus a, tincidunt justo. Sed imperdiet, lectus at efficitur vulputate,
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_shop_card.html.erb
<div class="card">
  <div class="card-container">
    <div class="card-content">
      <div class="left">
        <h3><%= shop.name %></h3>
        <p><%= shop.location %></p>
        <button class="card-button">Button</button>
      </div>
      <div class="right">
        <%= image_tag(shop.image_url, class: "card-image") %>
      </div>
    </div>
  </div>
</div>

app/views/shops/_shop_card.html.erb
<div class="card-content">
  <div class="left">
    <% if @shop.present? %>
      <h3><%= @shop.name %></h3>
      <p><%= @shop.location %></p>
    <% else %>
      <p>Shop not found.</p>
    <% end %>
    <button class="card-button">Button</button>
  </div>
</div>

app/views/shops/index.html.erb
<!DOCTYPE html>

<body>

  <%= render 'shared/navbar' %>

  <%= render 'shared/footer' %>

</body>

</html>

app/views/shops/show.html.erb
<h1>hello from shops show page</h1>